### ISSUE TITLE
.toDict() no longer converting nested DotMap to dict?

### ISSUE THREAD

**Issue by padthaitofuhot** [drgrib/dotmap#10]
I've been using DotMap for a while to make life easier. Today I came back to some code I'd let sit for a while and it looks like the new version of DotMap is no longer converting child DotMaps into dicts when the parent's .toDict() is called in arbitrarily-nested DotMaps.  Here's a snippet:

```
>>> conf.dep.toDict()
{'facts': {'replication_groups': [DotMap(name='rg1', members=['vdc1', 'vdc2'], options=DotMap(description='My RG'))],
```

In this snippet, `conf` is a top-level DotMap with child `dep`, who has many other children, some of whom are also DotMaps.

This was working six months ago... and I don't think bitrot could have broke it this bad :crystal_ball: 

Am I doing it wrong or did something undocumented change with DotMap?

**Comment by drgrib** [comment]
@padthaitofuhot This is a side effect of the feature added in #8. The constructor for the `DotMap` recursively converts all of the `dict` children inside of lists like this but I forgot to make `toDict` convert them back.

Can you post the `str` of `conf.dep` before calling `toDict`? That will help me correct the error faster.

**Comment by padthaitofuhot** [comment]
Sure thing!
```
>>> conf.dep
DotMap(facts=DotMap(operating_systems=DotMap(os_CentOS_7=True), virtual_data_centers=[DotMap(name='vdc1', members=['sp1'], options=DotMap(secret_key='badsecret', description='My First VDC')), DotMap(name='vdc2', members=['sp2'], options=DotMap(secret_key='badsecret', description='My Second VDC'))], install_node='192.168.2.200', replication_group_defaults=DotMap(full_replication=False, enable_rebalancing=False, description='Default replication group description', allow_all_namespaces=False), node_defaults=DotMap(ntp_servers=['192.168.2.2'], ecs_root_user='root', dns_servers=['192.168.2.2'], dns_domain='local', ecs_root_pass='ChangeMe'), storage_pools=[DotMap(name='sp1', members=['192.168.2.220'], options=DotMap(ecs_block_devices=['/dev/vdb'], description='My First SP')), DotMap(name='sp2', members=['192.168.2.221'], options=DotMap(protected=False, ecs_block_devices=['/dev/vdb'], description='My Second SP'))], storage_pool_defaults=DotMap(cold_storage_enabled=False, protected=False, ecs_block_devices=['/dev/vdc'], description='Default storage pool description'), virtual_data_center_defaults=DotMap(secret_key='badsecret', description='Default virtual data center description'), management_clients=['192.168.2.0/24'], replication_groups=[DotMap(name='rg1', members=['vdc1', 'vdc2'], options=DotMap(description='My RG'))]), lawyers=DotMap(license_accepted=True))
```

**Comment by drgrib** [comment]
@padthaitofuhot Okay. Give it a spin after a `pip install dotmap --upgrade`. Should work now.

**Comment by padthaitofuhot** [comment]
Sweet deal.  I really appreciate your fast response.  I'll give it a try and hollar back with any new issues.  Thank you.
