### ISSUE TITLE
DotMap fails for recursive structures

### ISSUE THREAD

**Issue by csachs** [drgrib/dotmap#12]
Setting a child value to the parent DotMap will lead to infinite recursions.
Especially this approach works fine for normal `dict`s.

```python
> some_dict = dict()
> some_dict['some_dict'] = some_dict
> print(some_dict)
{'some_dict': {...}}
```

```python
> from dotmap import DotMap
> some_dotmap = DotMap()
> some_dotmap.some_dotmap = some_dotmap
> print(some_dotmap)
> print(some_dotmap.toDict())

…
RecursionError: maximum recursion depth exceeded
```

Best regards, Christian

**Comment by drgrib** [comment]
@csachs Okay, I've added support for this because `dict` supports it. But, I have to say I find this application absolutely bizarre. 

Out of curiosity: when on earth would you use this in an application context? Or is this just a case of making the data structure mathematically and philosophically complete?

I'll need you to alert me to other methods that you need to support this self-referential functionality because I'm at a loss as to where else it would be needed.

**Comment by csachs** [comment]
Wow, thanks for the fast response!
No, I was actually trying to use it, and it failed, thus I reported it ;)
In my case I was working on a DI system. Imagine the following:
```python
from dotmap import DotMap

def print_person(name, location):
    print("%s lives in %s" % (name, location,))

john = DotMap()
john.name = "John Doe"
john.location = "London"

perform_di(print_person, john)
```
Now what if I want to have the 'whole' object in the called function?
```
def print_person2(person):
    print("%s lives in %s" % (person.name, person.location,))
    person.has_been_printed = True
```
Now I either 'explicitly' pass the name of what is passed to `perform_di`, or I once
```
john.person = john
```
and the function without additional infos would pass the object itself if `person` is requested as a parameter.

It's sorta hypothetical, as it's not code in use but rather stuff I'm currently writing, but that's my intended use ;)

Furthermore I can think of usage scenarios where DotMaps represent larger hierarchical trees where sub-trees are passed to a function, which _might_ need a 'link' to the root element attached somewhere (think filesystem).

Thanks again for quickly addressing this.
Best regards,
Christian

**Comment by drgrib** [comment]
@csachs Interesting. Okay. Yes I can see how the root level link may be relevant in special cases. Again, let me know if it breaks for other use cases and open a new issue. Glad the fast response was helpful.
