### ISSUE TITLE
DotMap.copy does not return an independent copy of the content

### ISSUE THREAD

**Issue by bastbnl** [drgrib/dotmap#13]
Currently copy() returns a reference to self, which means you're not working on an unique instance when working on the instance returned by copy()

``` 
>>> from dotmap import DotMap
>>> d1 = DotMap({'s': 1})
>>> d2 = d1.copy()
>>> d1.x = 2
>>> d1
DotMap(s=1, x=2)
>>> d2 
DotMap(s=1, x=2)
```

**Comment by drgrib** [comment]
@bastbnl Nice solution. Thanks for fixing it.
