### ISSUE TITLE
Support ** unpacking

### ISSUE THREAD

**Issue by patrick984** [drgrib/dotmap#15]
Is it possible to add support for *\* unpacking?

For example

``` python
def test(**kwargs):
    print(kwargs)

a = {'1':'a', '2':'b'}
b = DotMap(a)
test(**a)
test(**b)
```

This prints:

```
{'1': 'a', '2': 'b'}
{}
```

**Comment by drgrib** [comment]
As far as I can tell, I have implemented all the methods necessary to make this work:
http://stackoverflow.com/a/8601389/130427

For whatever reason, it doesn't. In the meantime, a workaround you can use is:

    test(**b.toDict())

Let me know if you figure out what `DotMap` is missing (or adding and obscuring) that is causing it not to unpack correctly via `**kwargs` directly.

**Comment by patrick984** [comment]
Upon further investagtion I was able to make keyword expansion work as expected by changing the DotMap class to inherit from MutableMapping instead of OrderedDict (as suggested here: http://stackoverflow.com/questions/11890066/making-custom-containers-work-with-kwargs-how-does-python-expand-the-args/11890526#comment15824502_11890066).

Diff: https://gist.github.com/patrick984/ceaa967a424ca60ebfea3ea641110d7b

**Comment by drgrib** [comment]
@patrick984 Excellent. Thanks for investigating. I've implemented your change into the latest version.
