### ISSUE TITLE
FR: _default parameter

### ISSUE THREAD

**Issue by xged** [drgrib/dotmap#16]
Be able to pass a default value which would act in the same way as an argument to `collections.defaultdict()`

**Comment by drgrib** [comment]
@xged Can you give me an example snippet of code using `DotMap` that you would like to function but isn't yet?

**Comment by drgrib** [comment]
@xged I'll resume work on this if you respond.

**Comment by Shadoukun** [comment]
defaultdict allows you to pass a callable to be called when non-existent keys in the dictionary are accessed, instead of raising a `KeyError`. 

```
>>> from collections import defaultdict
>>> ddict = defaultdict(lambda: None)

>>> print(ddict['foo'])
None

>>> ddict = defaultdict(list)
>>> print(dotmap.foo)
[]

>>> ddict = defaultdict(lambda: "foo")
>>> print(ddict['foo'])
foo
```

DotMap doesn't raise a `KeyError` either. It just returns DotMap. But you can't change this behaviour.

```
>>> from dotmap import DotMap 
>>> dotmap = DotMap()
DotMap()
```

**Comment by drgrib** [comment]
@Shadoukun This is because one of the core features of `DotMap` is to create `DotMap` children for non-existent keys. Per the README, this allows calls like the following to work:

```
m = DotMap()
m.people.steve.age = 31
```

**Comment by Shadoukun** [comment]
Yeah, I see that.

I was thinking behaviour like this. 

```
>>> m = DotMap(default=lambda: 'foo')
>>> m.people
'foo'
>>> m.people.phones
'foo'
>>> m.people.phones.mobile = "something"
>>> m.people
DotMap()
>>> m.people.phones
DotMap()
```

Which would allow for more defaultdict-like behaviour, without breaking the functionality you mention.

**Comment by drgrib** [comment]
@Shadoukun So are you expecting `m.people` to be change from `<class 'str'>` to `<class 'dotmap.DotMap'>` after  `m.people.phones` is executed? That would be a challenge and I'm not quite sure how to do it.
