### ISSUE TITLE
Error with copy.deepcopy()

### ISSUE THREAD

**Issue by robertocalandra** [drgrib/dotmap#17]
Performing a deep copy of a DotMap seems to result in an infinite loop that eventually end with the error:
 ```
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

Here is a code example that cause the crash:
```
import copy
from dotmap import DotMap
t = DotMap()
t.a = 1
t.b = 3
f = copy.deepcopy(t)
print(f)
```

PS: Thank you for this package, it is really great!

**Comment by drgrib** [comment]
Glad you are enjoying it!

This issue should be fixed now after you update.

**Comment by robertocalandra** [comment]
Thank you very much for the quick fix :)
