### ISSUE TITLE
Deepcopy in loop.

### ISSUE THREAD

**Issue by 2cadz** [drgrib/dotmap#18]
Hello,
Before starting thank you for this module.
I do not understand why this little piece of code does not return the expected result.

`import copy
from dotmap import DotMap
l = []
d = {'d1': {'d2': ''}}
m = DotMap(d)
for i in range(2):
....      x = copy.deepcopy(m)
....      x.d1.d2 = i
....      l.append(x)

print l
[DotMap(d1=DotMap(d2=1)), DotMap(d1=DotMap(d2=1))]
`

Expected result

`[DotMap(d1=DotMap(d2=0)), DotMap(d1=DotMap(d2=1))]`

Can you help me understand?
Regards.

**Comment by drgrib** [comment]
This was a bug. Thanks for catching it. You can get the fix by running `pip install dotmap --upgrade`.

**Comment by 2cadz** [comment]
Thanks, and thanks for the speed :-)
