### ISSUE TITLE
Integer in dictionary key.

### ISSUE THREAD

**Issue by 2cadz** [drgrib/dotmap#19]
Hello,

I have the error below with the following code:

```
>>> d = {1: 'a', 2: 'b'}
>>> m = DotMap(d)
>>> print m
DotMap(1='a', 2='b')
>>> m.1 = 'c'
  File "<stdin>", line 1
    m.1 = 'c'
      ^
SyntaxError: invalid syntax
```

We can not use an integer as a dictionary key?

Regards.

**Comment by drgrib** [comment]
@2cadz You can but you have to access it using the bracket `[]` notation, e.g. `m[1]`. The base Python language won't allow us to access numerical keys using dot-notation.

**Comment by 2cadz** [comment]
Thank you for your answer.
