### ISSUE TITLE
Accessing a key that does not exist does not through an error

### ISSUE THREAD

**Issue by shivakumargn** [drgrib/dotmap#28]
A dictionary throws an exception when a key that does not exist is accessed while DotMap does not.
It ideally should.

```
>>> from dotmap import DotMap
>>> a = { 'x':'one' }
>>> b = DotMap(a)
>>> a['y']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'y'
>>> b.y
DotMap()
```

**Comment by drgrib** [comment]
Implementing this would break the automatic hierarchy feature:

``` python
m = DotMap()

m.people.john.age = 32
m.people.john.job = 'programmer'
```

**Comment by YoelShoshan** [comment]
@drgrib I believe that the vast majority of people would prefer to have exception thrown for non-existing keys, over having hierarchical support.

Another idea is to throw exceptions when _dynamic=False

of course, I may be wrong :)

**Comment by drgrib** [comment]
@YoelShoshan As the creator, I designed it as one of my core features. So I have to disagree with you, even if I am the only one.

**Comment by YoelShoshan** [comment]
Perfectly understandable, thanks for sharing this repository either way :)
I switched to "munch" - which supports what I specifically need.

P.S. - I didn't dive too deeply, but it *seems* that they support both options - recursive attributes and throwing exceptions on invalid entries. I may be wrong. https://github.com/Infinidat/munch

Cheers.

**Comment by drgrib** [comment]
@YoelShoshan Thanks. `dotmap` supports both options too. You can find it in the readme under `DotMap(_dynamic=False)`.
