### ISSUE TITLE
Converting simple DotMap to dict works, but vice versa not

### ISSUE THREAD

**Issue by hearues-zueke-github** [drgrib/dotmap#30]
Here is a very simple example of what I mean with the title:

First create a an empty DotMap with an element of itself:
`dm = DotMap()`
`dm.dm = dm`
Which gives `DotMap(dm=DotMap(...))`.

Then convert it to a normal dict will also work:
`d = dm.toDict()`
Which gives `{'dm': {...}}`.

But when trying to convert `d` back to `dm` it gives an exception:
`RecursionError: maximum recursion depth exceeded while calling a Python object`.

Using Python 3.5.6 and dotmap version 1.2.20.
Also have a look to the picture:
![dot_map_resursion_fail](https://user-images.githubusercontent.com/7109889/45962755-e5ffcb00-c021-11e8-8bae-02d4ca72d4d7.png)

**Comment by drgrib** [comment]
I wouldn't call this a "simple" `DotMap`. I consider the requests I've received for recursive maps to be a pretty advanced feature. Anyhow, fixed in #37.

**Comment by hearues-zueke-github** [comment]
Yeah, you are right, but I thought only for a small example, where I can reproduce this error.

Also thank you for the fix too, now I can use the on some of my own problems written edge cases ^^.
