### ISSUE TITLE
DotMap objects not raising exception when member accessed before assignment

### ISSUE THREAD

**Issue by awolokita** [drgrib/dotmap#33]
Is this the intended behavior? My feeling is that DotMap should raise an exception e.g. AttributeError (or a subclass).

Example running dotmap version 1.2.39.

from dotmap import DotMap
m = DotMap(a=1, b=2)
m.a
Out[35]: 1
m.b
Out[36]: 2
m.c
Out[37]: DotMap(_repr_mimebundle_=DotMap())

**Comment by drgrib** [comment]
@awolokita Yes, that is the intended behavior. It is what enables this feature:

``` python
m = DotMap()
m.people.steve.age = 31
```

It can be disabled with `DotMap(_dynamic=False)`.
