### ISSUE TITLE
hasattr() does not return False if _dynamic=False

### ISSUE THREAD

**Issue by gingerbreadassassin** [drgrib/dotmap#42]
Because `hasattr` just uses `getattr` until `AttributeError` is raised, it always returns true when running `hasattr(DotMap(), 'foobar')` 

This is expected behavior, as in #33 

However, using `hasattr` raises `KeyError` if `_dynamic=False` is used:

```python
>>> from dotmap import DotMap
>>> foo = DotMap({'bar':'baz'}, _dynamic=False)
>>> hasattr(foo, 'bar')
True
>>> hasattr(foo, 'qux')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\...\venv\lib\site-packages\dotmap\__init__.py", line 85, in __getattr__
    return self[k]
  File "C:\...\venv\lib\site-packages\dotmap\__init__.py", line 73, in __getitem__
    return self._map[k]
KeyError: 'qux'
```

Would it be possible to handle `KeyError` by `hasattr` by returning `False`?

**Comment by FelixSchwarz** [comment]
Not sure when this was implemented but the code you posted now works as you proposed. :-)
