### ISSUE TITLE
List of DotMaps, Append

### ISSUE THREAD

**Issue by thestumbler** [drgrib/dotmap#47]
Not sure if this is a DotMap issue of a cockpit error, but I noticed a problem when appending dotmaps to a list inside a loop.  This code:

```python
import dotmap
mylist=[]
dd = DotMap()
for i in range(10,40,10):
    dd.apple = i+10
    dd.baker = i-10
    mylist.append(dd)
mylist
```
Produces the results below, which are not what I wanted:

```
[DotMap(apple=40, baker=20),
 DotMap(apple=40, baker=20),
 DotMap(apple=40, baker=20)]
```

Playing around some, by trial and error I discovered that moving the DotMap definition inside the loop gives the desired results:

```python
import dotmap
mylist=[]
for i in range(10,40,10):
    dd = DotMap()
    dd.apple = i+10
    dd.baker = i-10
    mylist.append(dd)
mylist
```

```
[DotMap(apple=20, baker=0),
 DotMap(apple=30, baker=10),
 DotMap(apple=40, baker=20)]
```

Is this the expected behavior?

**Comment by drgrib** [comment]
@thestumbler This isn't a `DotMap` issue, it is a Python syntax issue. You are appending references to the same object to a list multiple times when you really want new objects. You'll get the exact same results with a built-in `dict`:

``` python
mylist=[]
dd = {}
for i in range(10,40,10):
    dd['apple'] = i+10
    dd['baker'] = i-10
    mylist.append(dd)
print(mylist)
```

```
[{'apple': 40, 'baker': 20},
 {'apple': 40, 'baker': 20},
 {'apple': 40, 'baker': 20}]
```
