### ISSUE TITLE
Add a warning mode

### ISSUE THREAD

**Issue by PBrockmann** [drgrib/dotmap#5]
Would be nice to have a warning mode when you overwrite a value for a key already defined.

```python
from dotmap import DotMap
m = DotMap(warning=True)

m.author.reference="123"
m.author.reference="234"
Warning: overwrite author.reference 
```

**Comment by PBrockmann** [comment]
warning keyword would be internal and not a key/value preset.

**Comment by drgrib** [comment]
Thanks for the idea on this. I don't think this is the pattern I would want for this but I will have my eye out for possible ways of dealing with overwriting notification.
