### ISSUE TITLE
Publish latest changes to https://pypi.org/

### ISSUE THREAD

**Issue by vkropotko** [drgrib/dotmap#58]
Hello,

Could you please publish the latest version to pypi.org?
I would like to use `setdefault` functionality from this commit: https://github.com/drgrib/dotmap/commit/367404c91e462dbd20c2c0b43f56e16e4eafb4ad

**Comment by vkropotko** [comment]
@drgrib

**Comment by drgrib** [comment]
Updated in 6922b57e332c306c353696e1c6a3ac75829f84d6
