### ISSUE TITLE
If provided with invalid syntax, it inserts __members__ and __methods__ keys in a DotMap

### ISSUE THREAD

**Issue by niravsh** [drgrib/dotmap#6]
Hi,
This utility is very useful and the only thing I am worrying about using this is its robustness in handling corner cases. I encountered one as below:
 f = DotMap()
>>> f.MessageType = 'Message1'
>>> f
DotMap(MessageType='Message1')
>>> f.Header = DotMap('data1=value1')
>>> f
DotMap(MessageType='Message1'), Header=DotMap() - Did not add data1
>>> f.Header.Status = DotMap(Code=200 OK)
SyntaxError: invalid syntax
>>> f.Header.Status = DotMap('Code'='200 OK')
SyntaxError: keyword can't be an expression
>>> f.Header.Status = DotMap('Code=200 OK')
>>> f.Header
DotMap( __members__=DotMap(), __methods__=DotMap(), Status=DotMap())
>>> f.Header.Status
DotMap()
>>> f.Header.Status.Code
DotMap()
>>> f.Header.Status.Code = '200 OK'
>>> f
DotMap(MessageType='Message1', Header=DotMap(__members__=DotMap(), __methods__=DotMap(), Status=DotMap(Code='200 OK')))
>>> f.toDict()
{'Header': {** '__methods__': {}, '__members__': {},** 'Status': {'Code': '200 OK'}}, 'MessageType': 'Message1'}

I do not want the methods and members keys to be added,

**Comment by drgrib** [comment]
Thanks for the message. I'm not familiar with the API you are using but, yes, unfortunately, one of the drawbacks of the rapid hierarchy formation is that you have to check for membership first or delete unwanted members that are accidentally created. I can't really see a way around it given the Python base language.

Best,
Chris
