### ISSUE TITLE
Proposed update: By default, don't allow keys that mask dict functions

### ISSUE THREAD

**Issue by MrSurly** [drgrib/dotmap#69]
Propsal:

`x = DotMap({'get': 'mango'})` would result in a `KeyError`

`x = DotMap({'get': 'mango'}, _allow_all_keys=True)` would be fine, but now the `x.get` method would be `'mango'`

Granted this would likely break existing use cases.  Perhaps `x = DotMap({'get': 'mango'}, _prevent_method_masking=True)` would be better?

**Comment by drgrib** [comment]
I think it's a reasonable consideration and unlikely to break any reasonable use cases which has the flip side of making it an unlikely case to need to protect against in practice. I'm open to it's implementation if you are interested in considering it.

**Comment by MrSurly** [comment]
I'm OK with implementation if a PR would be welcome.  Otherwise, I'll likely implement for myself as a subclass.

**Comment by drgrib** [comment]
Sure thing. Probably `_prevent_method_masking` best communicates the purpose.
