### ISSUE TITLE
Deal with lists (iterable things) with dictionaries inside

### ISSUE THREAD

**Issue by filwaitman** [drgrib/dotmap#7]
Hi there!

Just wanna let you know that it breaks when you have a list of dictionaries.

----------------
Example:
```python
from dotmap import DotMap
FATHER = {
    'name': 'Father1',
    'children': [
        {'name': 'Child1'},
        {'name': 'Child2'},
        {'name': 'Child3'},
    ]
}


father = DotMap(FATHER)
print [x.name for x in father.children]
```

----------------
Expected:
```python
['Child1', 'Child2', 'Child3']
```

----------------
Got:
```python
AttributeError: 'dict' object has no attribute 'name'
```

**Comment by drgrib** [comment]
Right. Unfortunately, the current code only checks to convert child dictionaries to child DotMaps if they are the children of other dictionaries. Lists are currently copied over as-is. I'll investigate the possibility of converting the children of lists as well and implement it if it isn't too complex.

Best,
Chris

**Comment by drgrib** [comment]
Okay, this has been added to the current version. Upgrade using

    sudo pip install dotmap --upgrade

**Comment by filwaitman** [comment]
@drgrib confirmed, it's working!
Great work dude!  =)
