### ISSUE TITLE
No typed file for mypy?

### ISSUE THREAD

**Issue by fqlx** [drgrib/dotmap#78]
Is there a `dotmap.typed` file for mypy support?  I'd like to add typings to my project.

**Comment by drgrib** [comment]
Sorry, I don't even know what that is. I'm open to supporting PRs that don't break the tests though.

**Comment by fqlx** [comment]
It's adding types for type checking and hints - a feature from python 3.6+

For example:
```
from dataclasses import dataclass

@dataclass
class DataClassCard:
    rank: str
    suit: str

card: DataClassCard = DataClassCard('Q', 'Hearts')
```

If you set card to an integer instead of a `DataClassCard`, mypy will throw an error.

**Comment by drgrib** [comment]
Okay. I don't use Python for development anymore, so I'm not personally planning to add anymore code to the project but, again, I am open to PRs.

**Comment by fqlx** [comment]
In retrospect, the solution may be to use dataclasses for typing support + dotmap. I will close this issue out.
