### ISSUE TITLE
[Suggestion] Add support to avoid creating dynamic child creation

### ISSUE THREAD

**Issue by filwaitman** [drgrib/dotmap#8]
Hi folks!

I guess would be nice to have a way to avoid creating dynamic child creation. I know this dynamic child creation is here by design, but sometimes this isn't good (for instance, on tests: I would like to ensure I'm using the proper key names on some context)

Current scenario (Again, I know it's dynamic creating by design):
```
from dotmap import DotMap
>>> d = {'key': 'value'}
>>> dm = DotMap(d)
>>> dm.unexisting.key.i.would.like.to.see.burning
DotMap()
```

My suggestion is to add a way to avoid that, for instance:
```
from dotmap import DotMap
>>> d = {'key': 'value'}
>>> dm = DotMap(d, avoid_dynamic_child_creation=True)  # better name please.  =P
>>> dm.unexisting.key.i.would.like.to.see.burning
KeyError: 'unexisting'
```

Thanks!

**Comment by drgrib** [comment]
@filwaitman It makes sense as a feature probably something like this

    dm = DotMap(d, dynamic=False)

Unfortunately, the dynamic child creation is embedded pretty deeply into the design. You are welcome to take look at the source and see if you can find an straightforward path to implementing it.

Right now I remedy this situation by checking if keys are in the hierarchy first:

	k = 'unexisting'
	if k in dm:
		value = dm.unexisting

**Comment by drgrib** [comment]
@filwaitman Actually, this wasn't too bad. You can now use this feature after you `pip install dotmap --upgrade` with

   dm = DotMap(d, _dynamic=False)

**Comment by filwaitman** [comment]
@drgrib wow, that was fast.  o.O

Thanks for the attention, man!

I upgraded the version and tested it. It's working nicely on the root level of dict, but not still not working on inner dicts (on leaves, more precisely). Take a look:
```
>>> from dotmap import DotMap
>>> d = {'key': 'value', 'sub': {'inner_sub': {'key': 'value'}}}
>>> dm = DotMap(d, _dynamic=False)

>>> dm.unexisting  # exception raised
KeyError: 'unexisting'

>>> dm.sub.unexisting  # exception *not* raised
DotMap()

>>> dm.sub.inner_sub.unexisting  # exception *not* raised
DotMap()
```

Maybe you forgot to pass this parameter all the way down to the children `DotMap` creation (recursively I mean).

Anyway, thanks once again!

**Comment by drgrib** [comment]
Okay. Thanks for testing that. I've set child `DotMap`s from converted child `dict`s to inherit the `_dynamic` parameter. Give it another spin and let me know if it works right.

**Comment by drgrib** [comment]
@filwaitman Okay. Thanks for testing that. I've set each child `DotMap` from a converted child `dict` to inherit the `_dynamic` parameter from the parent `DotMap`. Give it another spin and let me know if it works right.

**Comment by filwaitman** [comment]
@drgrib Just tested it and worked nicely!

Thanks buddy! Great job!  =]
