### ISSUE TITLE
Handle keys with dashes by replacing with underlines

### ISSUE THREAD

**Issue by stocyr** [drgrib/dotmap#85]
It would be nice to change keys containing dashes (`'-'`) by replacing them with underlines (`'_'`), as in

```python
assert DotMap({'foo-bar': 1}, _dynamic=False).foo_bar == 1
```

**Comment by kalavt** [comment]
It would be nice to change keys containing dashes ('.') by replacing them with underlines ('_'), as in

`assert DotMap({'foo.bar': 1}, _dynamic=False).foo_bar == 1`

**Comment by drgrib** [comment]
Implemented in #86.

**Comment by jsivak** [comment]
Can we "not" do this, or have a configuration to prevent this from happening?

This change broke my handling of content from an .ini file that contains keys items  like this "mako.directories = pathname:templates", which get converted to a DotMap() structure where "mako.directories" is a key and the value is "pathname:templates".

With this new change, the keys are getting corrupted/changed without any notice (key "mako.directories" is now "mako_directories").

**Comment by drgrib** [comment]
Sorry about that @jsivak. I should have required new flags for these. I've reverted the change and you should have your functionality restored with the new update.

If you are interested in these features, @kalavt can you add them with the configurations `_dash_to_underscore=True` and `_period_to_underscore=True`, respectively? We won't want these active by default to avoid breaking changes.

**Comment by kalavt** [comment]
@drgrib I have created another pull request #89 
add key convert hook to support replace illegal characters or rename

@jsivak sorry for the inconvenience.

**Comment by jsivak** [comment]
Thanks for the quick turn-around.. much appreciated.

**Comment by drgrib** [comment]
Resolved in #89. You can now pass your own function to a `_key_convert_hook` argument in the constructor to change the keys however you want. Thanks for working on that @kalavt.
