### ISSUE TITLE
Unexpected behavior of `empty()`

### ISSUE THREAD

**Issue by tianhuil** [drgrib/dotmap#9]
If you type these lines into ipython:

```python
x=DotMap({'a': 'b'})
x.b.empty()  # True
print x.b
x.b.empty() # False
```

Inspecting a value should not change whether or not the field is empty.

**Comment by drgrib** [comment]
I'm getting True for both calls

	x = DotMap({'a': 'b'})
	print(x.b.empty()) # True (and creates empty DotMap for b)
	print(x.b) # Dotmap()
	print(x.b.empty()) # also True

Note that the second `b` is completely different from the value of `x.a` which is the string `'b'`.
