### ISSUE TITLE
key value which has '-' in it fails to work in dotmap

### ISSUE THREAD

**Issue by samcaspus** [drgrib/dotmap#92]
I tried creating a dictionary to DotMap

`sample_data = {"one-two" : 1}`
my understanding is after i change it to DotMap 
by doing this

`dotmap_data = DotMap(sample_data)`

I should be able to access it by doing `dotmap_data.one-two`

But for some reason its throwing me error
<img width="286" alt="image" src="https://user-images.githubusercontent.com/19220113/189280294-72913c49-4fce-48be-a515-2cbddb296b3b.png">

Is there any alternative way to resolve this using this package ?

Thanks

**Comment by drgrib** [comment]
Hi @samcaspus. What you are trying to do is invalid syntax in Python and has nothing to do with DotMap. The only way to access that value would be using `dotmap_data['one-two']`.

**Comment by samcaspus** [comment]
Got it I figured it would help fit my use case as i observed some open api specs have it in the custom data (x-custom-data)
Thanks for the info though @drgrib
