### ISSUE TITLE
Usage of dots in get() function

### ISSUE THREAD

**Issue by Fer-Jg** [drgrib/dotmap#93]
I have a dict that looks something like...
```json
"Something": {
  "Another": {
      "Filler": "y",
      "MaybeLast": {
          "ActualLast": {
              "key1": 1,
              "key2": 2
          },
          "Filler": "z"
      }
  },
  "Filler": "x"
}
```
So when I try to access `test_map.Something.Another.Filler` it works properly through that syntax (as expected), but if I try to access the same value by doing `test_map.get('Something.Another.Filler')` it returns None, I guess this is because DotMap inherits a Dict or maybe I'm just doing something wrong.

Tbh I don't know if this is an issue or a feature request lol

**Comment by drgrib** [comment]
I believe the syntax you would be looking for in that case would be `test_map.get('Something').get('Another').get('Filler')`. `DotMap` is implemented on the `.` syntax itself and can't be mixed and matched with direct key access using `get`.

**Comment by Fer-Jg** [comment]
Yes, getting to the last value through multiple `get()` would work, the thing is that I "don't know" what will be tried to be get (I am trying to use this for user input) so I don't know if  I need just 2 `get()` or 5 and I don't know the name of the keys that will be looked for, that is why I was suggesting something like the `get()` itself but maybe there could be another method like `get_nested()` or something similar so you can get the value from a nested Map without always knowing how nested it is.

**Comment by drgrib** [comment]
There may be an undocumented implementation of this already in the issues that you can init a DotMap with. I did quick search and couldn't find it, though. People have added a lot of extra features over the years that I haven't kept track of.

But my first thought when you say you don't know how many `get()` calls you need is why you wouldn't just do something like:

```
user_input = 'Something.Another.Filler'
m = test_map
prev = test_map
for k in user_input.split('.'):
    m = m.get(k)
print(m)
```

I just ran it on your original dict and got the expected value of
```
y
```

**Comment by Fer-Jg** [comment]
oh yeah, actually that's pretty useful, didn't think of that, thanks haha.
I also wanted to have this implementation because I am trying to also set the value for the determined input (I thought that if a new getter is implemented, there would also be a new setter), which is my major concern, I am trying to update the value from that nested dict through a dotted input.

**Comment by drgrib** [comment]
Glad you found it useful. There may be a more elegant way to do this but a setter could be added with a modification of the algorithm:

``` python
test_map = {"Something": {
  "Another": {
      "Filler": "y",
      "MaybeLast": {
          "ActualLast": {
              "key1": 1,
              "key2": 2
          },
          "Filler": "z"
      }
  },
  "Filler": "x"
}}

user_input = 'Something.Another.Filler'
m = test_map
prev = test_map
for k in user_input.split('.'):
    prev = m
    prev_k = k
    m = m.get(k)
print(m)

# set
prev[prev_k] = 'new_value'
print(test_map)
```
```
y
{'Something': {'Another': {'Filler': 'new_value', 'MaybeLast': {'ActualLast': {'key1': 1, 'key2': 2}, 'Filler': 'z'}}, 'Filler': 'x'}}
```

**Comment by Fer-Jg** [comment]
That's really smart!
Sorry for ghosting the thread, I got some stuff pending in front of me and ending up forgetting about this but I just tested it with the case I needed it for and it worked like a charm :)

Tysm! :D

**Comment by drgrib** [comment]
No problem :)
