### ISSUE TITLE
make it compatible with json.dumps

### ISSUE THREAD

**Issue by adminy** [drgrib/dotmap#96]
currently when I try json.dumps on a dotmap object, it just gives back an empty dictionary. I'd like for that to be seamless without calling the toJson() function.

Also any reason why the library is as far away from snake_case as possible? I'm afraid most linters will complain.

**Comment by drgrib** [comment]
I'm afraid I'm no longer actively developing this library. I stopped using Python for development years ago and primarily use Go now. I am open to reviewing merge requests that pass the tests, though.

**Comment by adminy** [comment]
Its ok, I found WizDot python library. Its far superior in every way, I'll continue using that. I haven't seen too many data scientists use Go so I'll stick with what they know best in the industry.

**Comment by drgrib** [comment]
It doesn't appear to support dynamic child creation using dot notation, which was my primary use case for DotMap personally when I created it. But if it meets your needs, that's great.
